// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $blog from "./routes/blog.tsx";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $images from "./routes/images.tsx";
import * as $index from "./routes/index.tsx";
import * as $BlogPosts from "./islands/BlogPosts.tsx";
import * as $ImageGallery from "./islands/ImageGallery.tsx";
import * as $effects_RainEffect from "./islands/effects/RainEffect.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_app.tsx": $_app,
		"./routes/_layout.tsx": $_layout,
		"./routes/blog.tsx": $blog,
		"./routes/blog/[slug].tsx": $blog_slug_,
		"./routes/images.tsx": $images,
		"./routes/index.tsx": $index,
	},
	islands: {
		"./islands/BlogPosts.tsx": $BlogPosts,
		"./islands/ImageGallery.tsx": $ImageGallery,
		"./islands/effects/RainEffect.tsx": $effects_RainEffect,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
